version: "3.8"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: rapidinner
    volumes:
      - Rapidinner_santt4na:/var/lib/mysql

volumes:
  Rapidinner_santt4na:
